### ISSUE TITLE
Identifying when Event Hubs is throttling the simulator

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#180]
We have logic in the simulator that is looking for `ServerBusyException`. We interpret this to mean that our event hub is throttling us (we are sending more events that it can handle). 
However, I have not been able to get this exception to fire.
- [ ] When should we expect this to fire? (Research, and put the answer in this issue.)
- [ ] What will it take to demonstrate this firing?

We want to be able to know with confidence when we are being throttled.

**Comment by bennage** [comment]
Here's the [list of exceptions](https://msdn.microsoft.com/en-us/library/azure/hh418082.aspx) that the .NET client library can throw.

**Comment by bennage** [comment]
I've been told that the expected exception is swallowed due ot the default RetryPolicy. I've tried setting this to `RetryPolicy.NoRetry` and when I do see I am seeing exceptions. However, I don't see the expected `ServerBusyException`.

**Comment by lbrader** [comment]
In the long running test 48 hour test.  I'm now seeing the ServerBusyException & TimeoutException.  I'm now only logging to file all exceptions.

Event Hub is set with 1 Scaling unit.  I'm provisioning 5000 devices.  

I'm seeing allot of the Server Busy Exceptions followed by many Timeout Exceptions.
After 48+ hours of running I have a 32MB error log file filled with those errors.

Will run a 2 hour test to characterize when those errors are firing.

**Comment by lbrader** [comment]
Related to #30

**Comment by hveiras** [comment]
I'm seeing lots of these exceptions when running the simulator locally with 2000 devices. I checked EventSource but I'm not seeing any ServerBusyException. I think my test is far from that, it seems I'm beeing limited by connections. 

ThreadID="9,980" FormattedMessage="out-connection211: Operation AsyncIoFault failed with error System.IO.IOException: The read operation failed, see inner exception. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at Microsoft.ServiceBus.Messaging.Amqp.Transport.TransportStream.EndRead(IAsyncResult asyncResult)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.EndRead(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Amqp.Transport.TlsTransport.HandleOperationComplete(IAsyncResult result, Boolean write, Boolean syncComplete)." source="out-connection211" operation="AsyncIoFault" message="System.IO.IOException: The read operation failed, see inner exception. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at Microsoft.ServiceBus.Messaging.Amqp.Transport.TransportStream.EndRead(IAsyncResult asyncResult)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.EndRead(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Amqp.Transport.TlsTransport.HandleOperationComplete(IAsyncResult result, Boolean write, Boolean syncComplete)"

**Comment by bennage** [comment]
I'm closing this issue, since I do not consider it blocking for our work.
