### ISSUE TITLE
Simulator fails on disposed object

### ISSUE THREAD

**Issue by hveiras** [mspnp/iot-journey#308]
Microsoft.Practices.IoTJourney.ScenarioSimulator.ConsoleHost

[1] Provision Devices
[2] Run NoErrorsExpected
[3] Run ThirtyDegreeReadings
[4] Exit

Select an option: 2
executing Run NoErrorsExpected
press `q` to signal termination
EventId : 5, Level : Informational, Message : , Payload : [hostName : hveirasX1]
 [scenario : NoErrorsExpected] , EventName : SimulationStartedInfo, Timestamp :
2015-09-02T21:16:15.5502344Z, ProcessId : 10336, ThreadId : 4648

an exception occurred
System.AggregateException: One or more errors occurred. ---> System.ObjectDispos
edException: Cannot access a disposed object.
   at System.Reactive.Subjects.Subject`1.Subscribe(IObserver`1 observer)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserv
er`1 observer)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Reactive.PlatformServices.DefaultExceptionServices.Rethrow(Exceptio
n exception)
   at System.Reactive.ExceptionHelpers.Throw(Exception exception)
   at System.Reactive.Stubs.<.cctor>b__1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.SumInt32._.OnError(Exception error)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserv
er`1 observer)
   at System.Reactive.Linq.ObservableImpl.SumInt32.Run(IObserver`1 observer, IDi
sposable cancel, Action`1 setSink)
   at System.Reactive.Producer`1.Run(IScheduler _, State x)
   at System.Reactive.Concurrency.ScheduledItem`2.InvokeCore()
   at System.Reactive.Concurrency.ScheduledItem`1.Invoke()
   at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(Schedule
rQueue`1 queue)
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState
 state, TimeSpan dueTime, Func`3 action)
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state,
Func`3 action)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enab
leSafeguard)
   at System.Reactive.Producer`1.Subscribe(IObserver`1 observer)
   at System.ObservableExtensions.Subscribe[T](IObservable`1 source, Action`1 on
Next)
   at Microsoft.Practices.IoTJourney.ScenarioSimulator.SimulationProfile.Observe
ScenarioOuput(IObservable`1 count) in d:\Dev\Repositories\mspnp\iot-journey-clon
e\src\Simulator\ScenarioSimulator\SimulationProfile.cs:line 78
   at Microsoft.Practices.IoTJourney.ScenarioSimulator.SimulationProfile.<RunSim
ulationAsync>d__b.MoveNext() in d:\Dev\Repositories\mspnp\iot-journey-clone\src\
Simulator\ScenarioSimulator\SimulationProfile.cs:line 111
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a dispos
ed object.
   at System.Reactive.Subjects.Subject`1.Subscribe(IObserver`1 observer)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserv
er`1 observer)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Reactive.PlatformServices.DefaultExceptionServices.Rethrow(Exceptio
n exception)
   at System.Reactive.ExceptionHelpers.Throw(Exception exception)
   at System.Reactive.Stubs.<.cctor>b__1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.SumInt32._.OnError(Exception error)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserv
er`1 observer)
   at System.Reactive.Linq.ObservableImpl.SumInt32.Run(IObserver`1 observer, IDi
sposable cancel, Action`1 setSink)
   at System.Reactive.Producer`1.Run(IScheduler _, State x)
   at System.Reactive.Concurrency.ScheduledItem`2.InvokeCore()
   at System.Reactive.Concurrency.ScheduledItem`1.Invoke()
   at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(Schedule
rQueue`1 queue)
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState
 state, TimeSpan dueTime, Func`3 action)
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state,
Func`3 action)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enab
leSafeguard)
   at System.Reactive.Producer`1.Subscribe(IObserver`1 observer)
   at System.ObservableExtensions.Subscribe[T](IObservable`1 source, Action`1 on
Next)
   at Microsoft.Practices.IoTJourney.ScenarioSimulator.SimulationProfile.Observe
ScenarioOuput(IObservable`1 count) in d:\Dev\Repositories\mspnp\iot-journey-clon
e\src\Simulator\ScenarioSimulator\SimulationProfile.cs:line 78
   at Microsoft.Practices.IoTJourney.ScenarioSimulator.SimulationProfile.<RunSim
ulationAsync>d__b.MoveNext() in d:\Dev\Repositories\mspnp\iot-journey-clone\src\
Simulator\ScenarioSimulator\SimulationProfile.cs:line 111<---

press any key to return to the menu

**Comment by bennage** [comment]
Yeah, this was a bug I introduced. Sorry.
